server:
  port: ${PORT:0}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

stats-service:
  id: stats-server

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    warehouse:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true

app:
  name: ${spring.application.name:main-service}
