CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(2000) NOT NULL,
    author_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
    updated TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    moderated_by BIGINT,
    moderated_at TIMESTAMP
);

CREATE INDEX idx_comments_event_id ON comments(event_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_status ON comments(status);
CREATE INDEX idx_comments_created ON comments(created);
CREATE INDEX idx_comments_moderated_by ON comments(moderated_by);