

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL, -- PENDING, CONFIRMED, REJECTED, CANCELED
    CONSTRAINT unique_event_requester UNIQUE (event_id, requester_id)
);
