-- schema.sql в модуле request-service
CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL, -- PENDING, CONFIRMED, REJECTED, CANCELED
    CONSTRAINT unique_event_requester UNIQUE (event_id, requester_id)
);

CREATE INDEX idx_requests_event_id ON requests(event_id);
CREATE INDEX idx_requests_requester_id ON requests(requester_id);