spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
        routes:
          - id: main-service-route
            uri: lb://MAIN-SERVER
            predicates:
              - Path=/admin/**
              - Path=/users/**
              - Path=/events/**
              - Path=/categories/**
              - Path=/compilations/**

          - id: ewm-stats-route
            uri: lb://EWM-STATS-SERVER
            predicates:
              - Path=/stats/**
              - Path=/hit/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
