server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        # ===================================================================
        # Routes for Categories
        # ===================================================================
        - id: categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**

        - id: categories-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/**

        # ===================================================================
        # Routes for Compilations
        # ===================================================================
        - id: compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**

        - id: compilations-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/compilations/**

        # ===================================================================
        # Routes for Event
        # ===================================================================
        - id: event
          uri: lb://main-service
          predicates:
            - Path=/events/**

        - id: event-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/events/**

        - id: event-private
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/events/**

        # ===================================================================
        # Routes for Request
        # ===================================================================
        - id: request
          uri: lb://main-service
          predicates:
            - Path=/users/{userId}/requests/**

        # ===================================================================
        # Routes for User Service
        # ===================================================================
        - id: user
          uri: lb://main-service
          predicates:
            - Path=/admin/users/**
